//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransactions
    {
        public int BankTransactionId { get; set; }
        public string TransactionDescription { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public Nullable<int> BankId { get; set; }
    
        public virtual Banks Banks { get; set; }
    }
}
